spring.application.name=DemoTest
spring.datasource.url=jdbc:mysql://localhost:3306/springboodemo
spring.datasource.username=root
spring.datasource.password=Ajam@2204

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true